'use client';

import { useState } from 'react';
import useSWR from 'swr';
import { Activity, AlertTriangle, Drill, Gauge, MapPin, Wrench, type LucideIcon } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { ProductionSectionShell } from '@/components/production/production-section-shell';

type PlanLine={id:string;line_type:string;mine_name_raw:string|null;sector_raw:string|null;level_raw:string|null;section_raw:string|null;planned_tons:number|null;planned_grade_pct:number|null;planned_advance_m:number|null;planned_drilling_m:number|null;priority:number|null};
type Report={id:string;operation_date:string;hole_code_raw:string|null;rig_name_raw:string;operator_name_raw:string|null;meter_initial:number|null;meter_final:number|null;drilled_meters:number|null;equipment_status_raw:string|null};
type LocationReviewRow={drill_hole_id:string;hole_code:string;resolution_state:string;report_count:number;last_report_date:string|null;source_site:string|null;candidate_mine_name:string|null;review_lane:string;review_priority:number;recommended_action:string;source_sites?:string[]|null;operational_bucket?:string;operational_priority?:number};
type Payload={summary:null|{report_rows:number;holes:number;rigs:number;operators:number;drilled_meters:number;out_of_service_reports:number;meter_capture_pct:number;min_date:string;max_date:string};monthly:Array<{month:string;rig_name_raw:string;mine_name_raw:string;shift_code_raw:string;report_count:number;drilled_meters:number;out_of_service_reports:number}>;maintenance:{assets:Array<{id:string;asset_name:string}>;schedules:Array<{id:string;asset_id:string;task_name:string;current_meter_snapshot:number|null;next_due_meter:number|null;frequency_hours:number|null}>;overdueSchedules:number};plan:null|{plan_code:string;period_start:string;period_end:string;total_mineral_to_plant_tons:number;target_cu_grade_pct:number;planned_drilling_m:number;planned_advance_m:number};planLines:PlanLine[];locationReview:{summary:{total:number;sourceConflicts:number;activeAugust:number;recentJuly:number;historical:number;mineKnownMissingSector:number;insufficientLocation:number};rows:LocationReviewRow[]};selectedRig:string|null;reports:Report[];lineage:{drillingSource:string;maintenanceSource:string;planSource:string;note:string}};
type Metric={label:string;value:string;icon:LucideIcon};
const fetcher=async(url:string):Promise<Payload>=>{const response=await fetch(url,{credentials:'include'});const data=await response.json();if(!response.ok)throw new Error(data.error||'No fue posible cargar Sondaje');return data;};
const fmt=(value:number|undefined|null,digits=0)=>value===null||value===undefined?'—':new Intl.NumberFormat('es-CL',{maximumFractionDigits:digits}).format(Number(value));
const lineLabel=(value:string)=>({mine_total:'Total mina',preparation:'Preparación',chamber:'Cámara',development:'Desarrollo',transport:'Transporte',radial_drilling:'Perforación radial',service:'Servicio'}[value]||value);
const dateLabel=(value:string|null)=>value?new Intl.DateTimeFormat('es-CL').format(new Date(`${value}T12:00:00`)):'—';

export default function SondajeProduccionPage(){
 const [selectedRig,setSelectedRig]=useState<string|null>(null);
 const {data,error,isLoading}=useSWR(`/api/produccion/sondaje${selectedRig?`?rig=${encodeURIComponent(selectedRig)}`:''}`,fetcher);
 const s=data?.summary;const assetsById=new Map((data?.maintenance.assets||[]).map(a=>[a.id,a.asset_name]));
 const metrics:Metric[]=[{label:'Metros perforados',value:s?`${fmt(s.drilled_meters,2)} m`:'—',icon:Drill},{label:'Reportes',value:s?fmt(s.report_rows):'—',icon:Activity},{label:'Pozos',value:s?fmt(s.holes):'—',icon:Gauge},{label:'Sondas',value:s?fmt(s.rigs):'—',icon:Wrench},{label:'Fuera de servicio',value:s?fmt(s.out_of_service_reports):'—',icon:AlertTriangle}];
 const location=data?.locationReview;
 return <ProductionSectionShell eyebrow="Producción · Sondaje" title="Sondaje de Producción" description="Ejecución histórica de sondajes, disponibilidad de equipos, plan mensual y calidad de ubicación, con ACTUAL y PLAN separados." capabilities={['Metros y pozos ejecutados','Actividad por sonda y turno','Disponibilidad y fallas reportadas','Mantención preventiva por horómetro','Programa mensual separado del actual','Revisión priorizada de ubicación de pozos']}>
  {error?<Card><CardContent className="pt-5 text-sm text-destructive">{error.message}</CardContent></Card>:null}
  <section className="grid gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-2 xl:grid-cols-5">{metrics.map(metric=>{const Icon=metric.icon;return <div key={metric.label} className="bg-card px-5 py-4"><div className="flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground">{metric.label}</p><Icon className="h-4 w-4 text-muted-foreground"/></div><p className="mt-2 text-2xl font-semibold tracking-tight">{isLoading?'—':metric.value}</p></div>})}</section>

  <Card>
   <CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><MapPin className="h-4 w-4"/>Ubicación de pozos · revisión priorizada</CardTitle><CardDescription>Conflictos y pozos activos aparecen primero; la deuda histórica queda separada para no contaminar la operación actual.</CardDescription></div><Badge variant={(location?.summary.sourceConflicts||0)+(location?.summary.activeAugust||0)>0?'destructive':'outline'}>{location?.summary.total||0} pendientes</Badge></div></CardHeader>
   <CardContent className="space-y-4">
    <div className="grid gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-2 xl:grid-cols-4">
     <div className="bg-card p-4"><p className="text-xs text-muted-foreground">Conflictos de fuente</p><p className="mt-1 text-2xl font-semibold">{location?.summary.sourceConflicts??'—'}</p></div>
     <div className="bg-card p-4"><p className="text-xs text-muted-foreground">Activos en agosto</p><p className="mt-1 text-2xl font-semibold">{location?.summary.activeAugust??'—'}</p></div>
     <div className="bg-card p-4"><p className="text-xs text-muted-foreground">Recientes de julio</p><p className="mt-1 text-2xl font-semibold">{location?.summary.recentJuly??'—'}</p></div>
     <div className="bg-card p-4"><p className="text-xs text-muted-foreground">Históricos</p><p className="mt-1 text-2xl font-semibold">{location?.summary.historical??'—'}</p></div>
    </div>
    <div className="overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead>Pozo</TableHead><TableHead>Mina / sitio</TableHead><TableHead>Último reporte</TableHead><TableHead className="text-right">Reportes</TableHead><TableHead>Qué falta</TableHead></TableRow></TableHeader><TableBody>{(location?.rows||[]).slice(0,20).map(row=><TableRow key={row.drill_hole_id}><TableCell className="font-medium">{row.hole_code}</TableCell><TableCell>{row.review_lane==='conflicto_fuente'&&row.source_sites?.length?row.source_sites.join(' ↔ '):(row.candidate_mine_name||row.source_site||'Sin ubicación acreditada')}</TableCell><TableCell>{dateLabel(row.last_report_date)}</TableCell><TableCell className="text-right tabular-nums">{fmt(row.report_count)}</TableCell><TableCell><div className="space-y-1"><Badge variant={(row.operational_priority||row.review_priority)>=90?'destructive':'outline'}>{row.review_lane==='conflicto_fuente'?'Resolver conflicto':row.review_lane==='mina_conocida_falta_sector'?'Confirmar sector':'Solicitar evidencia'}</Badge><p className="max-w-md text-xs text-muted-foreground">{row.recommended_action}</p></div></TableCell></TableRow>)}</TableBody></Table></div>
   </CardContent>
  </Card>

  <div className="grid gap-4 xl:grid-cols-2">
   <Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>Plan activo</CardTitle><CardDescription>Programa mensual separado de la ejecución real.</CardDescription></div><Badge variant="outline">PLAN</Badge></div></CardHeader><CardContent>{data?.plan?<div className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-muted-foreground">Mineral a planta</p><p className="mt-1 font-medium">{fmt(data.plan.total_mineral_to_plant_tons)} t</p></div><div><p className="text-muted-foreground">Ley objetivo Cu</p><p className="mt-1 font-medium">{fmt(data.plan.target_cu_grade_pct,2)}%</p></div><div><p className="text-muted-foreground">Perforación programada</p><p className="mt-1 font-medium">{fmt(data.plan.planned_drilling_m)} m</p></div><div><p className="text-muted-foreground">Avance programado</p><p className="mt-1 font-medium">{fmt(data.plan.planned_advance_m)} m</p></div></div>:<p className="text-sm text-muted-foreground">Sin plan activo.</p>}</CardContent></Card>
   <Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>Mantención de sondas</CardTitle><CardDescription>Pautas preventivas por horómetro.</CardDescription></div><Badge variant={data?.maintenance.overdueSchedules?'destructive':'outline'}>{data?.maintenance.overdueSchedules||0} vencidas</Badge></div></CardHeader><CardContent className="px-0 pb-0"><Table><TableHeader><TableRow><TableHead>Equipo</TableHead><TableHead>Tarea</TableHead><TableHead className="text-right">Actual / próxima</TableHead></TableRow></TableHeader><TableBody>{(data?.maintenance.schedules||[]).slice(0,8).map(row=><TableRow key={row.id}><TableCell>{assetsById.get(row.asset_id)||'Equipo'}</TableCell><TableCell>{row.task_name}</TableCell><TableCell className="text-right tabular-nums">{fmt(row.current_meter_snapshot)} / {fmt(row.next_due_meter)} h</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  </div>
  <Card><CardHeader><CardTitle>Detalle del plan mensual</CardTitle><CardDescription>{data?.plan?`${data.plan.plan_code} · ${data.planLines.length} líneas programadas`:'Sin plan activo'}</CardDescription></CardHeader><CardContent className="px-0 pb-0"><Table><TableHeader><TableRow><TableHead>Tipo</TableHead><TableHead>Mina / sector</TableHead><TableHead>Nivel / sección</TableHead><TableHead className="text-right">Ton</TableHead><TableHead className="text-right">Avance m</TableHead><TableHead className="text-right">Perforación m</TableHead></TableRow></TableHeader><TableBody>{(data?.planLines||[]).map(row=><TableRow key={row.id}><TableCell className="font-medium">{lineLabel(row.line_type)}</TableCell><TableCell>{[row.mine_name_raw,row.sector_raw].filter(Boolean).join(' · ')||'—'}</TableCell><TableCell>{[row.level_raw,row.section_raw].filter(Boolean).join(' · ')||'—'}</TableCell><TableCell className="text-right tabular-nums">{fmt(row.planned_tons)}</TableCell><TableCell className="text-right tabular-nums">{fmt(row.planned_advance_m)}</TableCell><TableCell className="text-right tabular-nums">{fmt(row.planned_drilling_m)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  <Card><CardHeader><CardTitle>Actividad reciente por equipo</CardTitle><CardDescription>Selecciona una sonda para abrir sus reportes fuente.</CardDescription></CardHeader><CardContent className="px-0 pb-0"><Table><TableHeader><TableRow><TableHead>Mes</TableHead><TableHead>Sonda</TableHead><TableHead>Mina</TableHead><TableHead>Turno</TableHead><TableHead className="text-right">Reportes</TableHead><TableHead className="text-right">Metros</TableHead><TableHead className="text-right">Fuera servicio</TableHead></TableRow></TableHeader><TableBody>{(data?.monthly||[]).slice(0,30).map((row,index)=><TableRow key={`${row.month}-${row.rig_name_raw}-${row.shift_code_raw}-${index}`} className="cursor-pointer" onClick={()=>setSelectedRig(row.rig_name_raw)}><TableCell>{new Intl.DateTimeFormat('es-CL',{month:'short',year:'numeric'}).format(new Date(`${row.month}T12:00:00`))}</TableCell><TableCell className="font-medium text-primary">{row.rig_name_raw}</TableCell><TableCell>{row.mine_name_raw}</TableCell><TableCell>{row.shift_code_raw||'—'}</TableCell><TableCell className="text-right tabular-nums">{fmt(row.report_count)}</TableCell><TableCell className="text-right tabular-nums">{fmt(row.drilled_meters,2)}</TableCell><TableCell className="text-right tabular-nums">{fmt(row.out_of_service_reports)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  {selectedRig?<Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>Detalle · {selectedRig}</CardTitle><CardDescription>Reportes fuente, pozos, operador, metros y estado.</CardDescription></div><button className="text-sm text-muted-foreground hover:text-foreground" onClick={()=>setSelectedRig(null)}>Cerrar</button></div></CardHeader><CardContent className="px-0 pb-0"><Table><TableHeader><TableRow><TableHead>Fecha</TableHead><TableHead>Pozo</TableHead><TableHead>Operador</TableHead><TableHead className="text-right">Inicial</TableHead><TableHead className="text-right">Final</TableHead><TableHead className="text-right">Metros</TableHead><TableHead>Estado</TableHead></TableRow></TableHeader><TableBody>{(data?.reports||[]).map(row=><TableRow key={row.id}><TableCell>{new Intl.DateTimeFormat('es-CL').format(new Date(`${row.operation_date}T12:00:00`))}</TableCell><TableCell className="font-medium">{row.hole_code_raw||'—'}</TableCell><TableCell>{row.operator_name_raw||'—'}</TableCell><TableCell className="text-right tabular-nums">{fmt(row.meter_initial,2)}</TableCell><TableCell className="text-right tabular-nums">{fmt(row.meter_final,2)}</TableCell><TableCell className="text-right tabular-nums">{fmt(row.drilled_meters,2)}</TableCell><TableCell><Badge variant={row.equipment_status_raw==='FUERA DE SERVICIO'?'destructive':'outline'}>{row.equipment_status_raw||'Sin estado'}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>:null}
  <p className="text-xs text-muted-foreground">Fuente: {data?.lineage.drillingSource||'Reporte_Sondajes_I_A.xlsx'} · {data?.lineage.note||''}</p>
 </ProductionSectionShell>;
}
