'use client';

import { FormEvent, useMemo, useState } from 'react';
import useSWR from 'swr';
import { AlertTriangle, CheckCircle2, ExternalLink, RefreshCw, Replace, ShieldAlert } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

type Item = {
  product_id: string; product_code: string; name: string; family: string | null; unit: string | null;
  inventory_snapshot_date: string | null; quantity_on_hand: number; quantity_reserved: number; quantity_available: number; minimum_required: number;
  wo_quantity_requested: number; outbound_quantity: number; work_order_count: number; affected_assets: number; shortage_quantity: number; shortage_work_orders: number;
  purchase_line_count: number; purchased_quantity: number; supplier_count: number; last_purchase_date: string | null; committed_lead_days: number | null; observed_lead_days: number | null;
  approved_relation_count: number; approved_obsolete: boolean; priority: 'critical' | 'high' | 'attention'; priority_reason: string;
};
type Relation = { id: string; relation_type: string; status: string; reason: string; evidence_reference: string | null; approved_at: string | null; source_product: { id: string; code: string; name: string } | null; target_product: { id: string; code: string; name: string } | null };
type Data = { counts: Record<string, number>; items: Item[]; relations: Relation[]; generatedAt: string };
const fetcher = async (url: string) => { const res = await fetch(url, { credentials: 'include' }); const body = await res.json().catch(() => null); if (!res.ok) throw new Error(body?.error || 'No se pudo cargar'); return body as Data; };
const n = (value: unknown) => Number(value || 0).toLocaleString('es-CL', { maximumFractionDigits: 1 });

export default function CriticalSparesPage() {
  const { data, error, isLoading, mutate } = useSWR('/api/inventory/critical-spares', fetcher, { revalidateOnFocus: false });
  const [priority, setPriority] = useState('all'); const [query, setQuery] = useState('');
  const [source, setSource] = useState<Item | null>(null); const [relationType, setRelationType] = useState('replacement'); const [targetCode, setTargetCode] = useState(''); const [reason, setReason] = useState(''); const [evidence, setEvidence] = useState(''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const items = useMemo(() => (data?.items || []).filter((item) => (priority === 'all' || item.priority === priority) && (!query.trim() || `${item.product_code} ${item.name} ${item.family || ''}`.toLowerCase().includes(query.trim().toLowerCase()))), [data?.items, priority, query]);

  async function propose(event: FormEvent) {
    event.preventDefault(); if (!source || !reason.trim() || (relationType !== 'obsolete' && !targetCode.trim())) return;
    setSaving(true); setMessage(null);
    const res = await fetch('/api/inventory/critical-spares', { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sourceProductId: source.product_id, relationType, targetProductCode: targetCode.trim(), reason: reason.trim(), evidenceReference: evidence.trim() || null }) });
    const body = await res.json().catch(() => null); setSaving(false);
    if (!res.ok) { setMessage(body?.error || 'No se pudo registrar la propuesta.'); return; }
    setMessage('Propuesta registrada. No tendrá efecto técnico hasta ser aprobada.'); setSource(null); setTargetCode(''); setReason(''); setEvidence(''); await mutate();
  }
  async function changeRelation(id: string, status: string) {
    setMessage(null); const res = await fetch('/api/inventory/critical-spares', { method: 'PATCH', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id, status }) }); const body = await res.json().catch(() => null); if (!res.ok) { setMessage(body?.error || 'No se pudo actualizar.'); return; } setMessage(status === 'approved' ? 'Relación aprobada y trazable.' : 'Relación actualizada.'); await mutate();
  }

  const c = data?.counts || {};
  return <div className="space-y-6">
    <section className="flex flex-col gap-4 border-b border-border/70 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-medium text-muted-foreground">Abastecimiento · Mantenimiento</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Repuestos críticos y obsolescencia</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Prioriza con stock canónico, demanda registrada y compras históricas. Las sustituciones solo son válidas después de una aprobación explícita.</p></div><Button variant="outline" onClick={() => void mutate()}><RefreshCw className="mr-2 h-4 w-4"/>Actualizar</Button></section>
    {message && <Card className="shadow-none"><CardContent className="p-4 text-sm">{message}</CardContent></Card>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Críticos', c.critical || 0], ['Prioridad alta', c.high || 0], ['Atención', c.attention || 0], ['Con demanda operacional', c.with_operational_demand || 0], ['Relaciones aprobadas', c.approved_lifecycle_relations || 0]].map(([label,value]) => <Card key={String(label)} className="shadow-none"><CardContent className="p-4"><p className="text-2xl font-semibold">{Number(value).toLocaleString('es-CL')}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></CardContent></Card>)}</div>
    <Card className="shadow-none"><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_220px]"><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar código, producto o familia"/><Select value={priority} onValueChange={setPriority}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todas las prioridades</SelectItem><SelectItem value="critical">Críticos</SelectItem><SelectItem value="high">Prioridad alta</SelectItem><SelectItem value="attention">Atención</SelectItem></SelectContent></Select></CardContent></Card>
    <Card className="shadow-none"><CardHeader><CardTitle className="text-lg">Prioridades verificables · {items.length.toLocaleString('es-CL')}</CardTitle></CardHeader><CardContent className="p-0">{error ? <p className="p-6 text-sm text-muted-foreground">No se pudo cargar la evaluación.</p> : isLoading ? <p className="p-6 text-sm text-muted-foreground">Evaluando existencias y demanda…</p> : items.length === 0 ? <p className="p-8 text-center text-sm text-muted-foreground">No hay condiciones para este filtro.</p> : <div className="divide-y border-t">{items.slice(0, 500).map((item) => <div key={item.product_id} className="p-4"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge variant={item.priority === 'critical' ? 'destructive' : 'outline'}>{item.priority === 'critical' ? 'Crítico' : item.priority === 'high' ? 'Prioridad alta' : 'Atención'}</Badge>{item.approved_obsolete && <Badge variant="secondary">Obsoleto aprobado</Badge>}<span className="font-mono text-xs text-muted-foreground">{item.product_code}</span></div><p className="mt-2 font-medium">{item.name}</p><p className="mt-1 text-sm text-muted-foreground">{item.priority_reason}</p><div className="mt-3 grid gap-x-6 gap-y-1 text-xs text-muted-foreground sm:grid-cols-2 lg:grid-cols-4"><span>Disponible: <strong className="text-foreground">{n(item.quantity_available)}</strong></span><span>Mínimo: <strong className="text-foreground">{n(item.minimum_required)}</strong></span><span>OT: <strong className="text-foreground">{n(item.work_order_count)}</strong></span><span>Equipos afectados: <strong className="text-foreground">{n(item.affected_assets)}</strong></span><span>Salidas registradas: <strong className="text-foreground">{n(item.outbound_quantity)}</strong></span><span>Líneas de compra: <strong className="text-foreground">{n(item.purchase_line_count)}</strong></span><span>Plazo observado: <strong className="text-foreground">{item.observed_lead_days == null ? 'Sin dato' : `${n(item.observed_lead_days)} días`}</strong></span><span>Snapshot stock: <strong className="text-foreground">{item.inventory_snapshot_date || 'Sin fecha'}</strong></span></div></div><div className="flex shrink-0 flex-wrap gap-2"><Button size="sm" variant="outline" asChild><a href={`/dashboard/bodega/productos-360?productId=${item.product_id}`}><ExternalLink className="mr-2 h-4 w-4"/>Producto 360°</a></Button><Button size="sm" onClick={() => { setSource(item); setRelationType('replacement'); setTargetCode(''); setReason(''); setEvidence(''); }}><Replace className="mr-2 h-4 w-4"/>Gestionar ciclo</Button></div></div></div>)}</div>}</CardContent></Card>
    {source && <Card className="border-primary/30 shadow-none"><CardHeader><CardTitle className="text-lg">Proponer relación técnica · {source.product_code}</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={propose}><div className="space-y-2"><Label>Tipo</Label><Select value={relationType} onValueChange={setRelationType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="replacement">Reemplazo</SelectItem><SelectItem value="substitute">Sustituto</SelectItem><SelectItem value="obsolete">Obsoleto sin reemplazo</SelectItem></SelectContent></Select></div>{relationType !== 'obsolete' && <div className="space-y-2"><Label>Código exacto del producto destino</Label><Input value={targetCode} onChange={(e) => setTargetCode(e.target.value)} placeholder="Código canónico"/></div>}<div className="space-y-2"><Label>Fundamento técnico</Label><Textarea rows={4} value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Documento, fabricante, ingeniería o validación que respalda la relación."/></div><div className="space-y-2"><Label>Evidencia</Label><Input value={evidence} onChange={(e) => setEvidence(e.target.value)} placeholder="Folio, documento, URL o referencia"/></div><div className="flex gap-2"><Button disabled={saving}>Registrar propuesta</Button><Button type="button" variant="ghost" onClick={() => setSource(null)}>Cancelar</Button></div></form></CardContent></Card>}
    <Card className="shadow-none"><CardHeader><CardTitle className="text-lg">Sustituciones y obsolescencia</CardTitle></CardHeader><CardContent className="space-y-3">{(data?.relations || []).length === 0 ? <p className="text-sm text-muted-foreground">No hay relaciones registradas.</p> : data?.relations.map((relation) => <div key={relation.id} className="rounded-lg border p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap gap-2"><Badge variant={relation.status === 'approved' ? 'secondary' : 'outline'}>{relation.status === 'approved' ? 'Aprobado' : relation.status === 'proposed' ? 'Propuesto' : relation.status === 'rejected' ? 'Rechazado' : 'Inactivo'}</Badge><Badge variant="outline">{relation.relation_type === 'replacement' ? 'Reemplazo' : relation.relation_type === 'substitute' ? 'Sustituto' : 'Obsoleto'}</Badge></div><p className="mt-2 text-sm font-medium">{relation.source_product ? `${relation.source_product.code} · ${relation.source_product.name}` : 'Producto origen'}</p>{relation.target_product && <p className="mt-1 text-sm text-muted-foreground">→ {relation.target_product.code} · {relation.target_product.name}</p>}<p className="mt-2 text-sm text-muted-foreground">{relation.reason}</p>{relation.evidence_reference && <p className="mt-1 text-xs text-muted-foreground">Evidencia: {relation.evidence_reference}</p>}</div>{relation.status === 'proposed' && <div className="flex gap-2"><Button size="sm" onClick={() => void changeRelation(relation.id, 'approved')}><CheckCircle2 className="mr-2 h-4 w-4"/>Aprobar</Button><Button size="sm" variant="outline" onClick={() => void changeRelation(relation.id, 'rejected')}>Rechazar</Button></div>}{relation.status === 'approved' && <Button size="sm" variant="outline" onClick={() => void changeRelation(relation.id, 'inactive')}>Desactivar</Button>}</div></div>)}</CardContent></Card>
    <p className="text-xs text-muted-foreground"><ShieldAlert className="mr-1 inline h-3.5 w-3.5"/>La compra histórica demuestra abastecimiento, no consumo. Si no existen movimientos, requerimientos de OT o plazos registrados, Motil muestra “sin dato” y no los infiere. <AlertTriangle className="ml-2 mr-1 inline h-3.5 w-3.5"/>Una propuesta de sustitución no tiene validez operativa hasta ser aprobada.</p>
  </div>;
}
