'use client';

import useSWR from 'swr';
import { ProduccionDashboard } from '@/components/dashboard/produccion-dashboard';
import { Badge } from '@/components/ui/badge';

type O={quality:{status:'PASS'|'HOLD';pass:number;hold:number};currentPeriod:null|{dataThrough:string;treatedTons:number;avgHeadGradePct:number|null;avgRecoveryPct:number|null;plan:null|{treatmentProgressPct:number|null;paceIndexPct:number|null}};intelligence:Array<{level:'info'|'watch'|'alert';code:string;title:string;detail:string}>};
const f=async(u:string):Promise<O>=>{const r=await fetch(u,{credentials:'include',cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);return j};
const p=(v:number|null|undefined,d=1)=>v==null?'—':`${v.toLocaleString('es-CL',{maximumFractionDigits:d})}%`;
export default function ProduccionPage(){const {data}=useSWR<O>('/api/produccion/canonical-overview',f,{revalidateOnFocus:false});const x=data?.currentPeriod,plan=x?.plan,alerts=data?.intelligence.filter(s=>s.level==='alert')||[],watch=data?.intelligence.filter(s=>s.level==='watch')||[],top=[...alerts,...watch].slice(0,3),critical=alerts.length+(data?.quality.status==='HOLD'?1:0),pace=plan?.paceIndexPct??null;return <div className="space-y-6">{data?<section className="overflow-hidden rounded-lg border bg-card"><div className="p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Producción · Centro de Control Ejecutivo</p><div className="mt-2 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold">Estado de la mina</h1><Badge variant={critical?'destructive':watch.length?'secondary':'outline'}>{critical?'Atención requerida':watch.length?'Con observaciones':'Operación estable'}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{critical?`${critical} asuntos requieren atención.`:watch.length?`${watch.length} señales en observación.`:'Sin desviaciones críticas en la evidencia disponible.'}</p></div><div className="grid gap-px border-t bg-border sm:grid-cols-2 xl:grid-cols-6"><K l="Tratado" v={x?`${x.treatedTons.toLocaleString('es-CL',{maximumFractionDigits:1})} t`:'—'}/><K l="Ritmo" v={pace==null?'—':pace>=97?'En ritmo':pace>=90?'Leve desvío':'Bajo ritmo'}/><K l="Avance plan" v={p(plan?.treatmentProgressPct)}/><K l="Ley cabeza Cu" v={p(x?.avgHeadGradePct,3)}/><K l="Recuperación" v={p(x?.avgRecoveryPct,2)}/><K l="Calidad" v={`${data.quality.pass} PASS · ${data.quality.hold} HOLD`}/></div><div className="border-t p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Lo que requiere atención</p><div className="mt-3 grid gap-3 lg:grid-cols-3">{top.length?top.map(s=><div key={s.code} className="rounded-lg border p-4"><div className="flex items-center gap-2"><p className="text-sm font-medium">{s.title}</p><Badge variant={s.level==='alert'?'destructive':'secondary'}>{s.level==='alert'?'Crítico':'Observar'}</Badge></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{s.detail}</p></div>):<div className="rounded-lg border p-4 text-sm text-muted-foreground">Sin señales prioritarias para este período.</div>}</div></div></section>:null}<ProduccionDashboard /></div>}
function K({l,v}:{l:string;v:string}){return <div className="bg-card p-4"><p className="text-xs text-muted-foreground">{l}</p><p className="mt-2 text-lg font-semibold tabular-nums">{v}</p></div>}
