'use client';

import { FormEvent, useMemo, useState } from 'react';
import useSWR from 'swr';
import { CheckCircle2, ExternalLink, GitBranch, PackageSearch, Plus, RefreshCw, XCircle } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

type BomItem = { id:string; status:string; component_code:string|null; component_name:string; component_path:string|null; quantity_required:number; reason:string; evidence_reference:string|null; asset:any; product:any; stock:any; operational:any };
type Data = { counts:{ total:number; approved:number; proposed:number; products:number; assets:number }; items:BomItem[]; whereUsed:any[] };
const fetcher = async (url:string) => { const r=await fetch(url,{credentials:'include'}); const p=await r.json().catch(()=>null); if(!r.ok) throw new Error(p?.error||'No se pudo cargar'); return p as Data; };

export default function TechnicalBomPage(){
  const {data,error,isLoading,mutate}=useSWR('/api/maintenance/technical-bom',fetcher,{revalidateOnFocus:false});
  const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [showForm,setShowForm]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
  const [form,setForm]=useState({assetCode:'',productCode:'',componentCode:'',componentName:'',componentPath:'',quantityRequired:'1',reason:'',evidenceReference:''});
  const filtered=useMemo(()=> (data?.items||[]).filter(row=>{ if(status!=='all'&&row.status!==status)return false; const q=query.trim().toLowerCase(); return !q||`${row.asset?.asset_code||''} ${row.asset?.name||''} ${row.product?.product_code||''} ${row.product?.name||''} ${row.component_code||''} ${row.component_name}`.toLowerCase().includes(q);}),[data?.items,query,status]);
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage(null);const r=await fetch('/api/maintenance/technical-bom',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({...form,quantityRequired:Number(form.quantityRequired)})});const p=await r.json().catch(()=>null);setSaving(false);if(!r.ok){setMessage(p?.error||'No se pudo guardar.');return;}setMessage('Relación propuesta. Debe aprobarse antes de considerarse parte de la BOM técnica.');setShowForm(false);setForm({assetCode:'',productCode:'',componentCode:'',componentName:'',componentPath:'',quantityRequired:'1',reason:'',evidenceReference:''});await mutate();}
  async function changeStatus(id:string,next:string){setMessage(null);const r=await fetch('/api/maintenance/technical-bom',{method:'PATCH',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({id,status:next})});const p=await r.json().catch(()=>null);if(!r.ok){setMessage(p?.error||'No se pudo actualizar.');return;}await mutate();}
  const counts=data?.counts;
  return <div className="space-y-6">
    <section className="flex flex-col gap-4 border-b border-border/70 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-medium text-muted-foreground">Mantenimiento · Activos</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">BOM técnica</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Relaciona equipo, componente y repuesto canónico con aprobación explícita. No se crean compatibilidades por similitud de nombre.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void mutate()}><RefreshCw className="mr-2 h-4 w-4"/>Actualizar</Button><Button onClick={()=>setShowForm(v=>!v)}><Plus className="mr-2 h-4 w-4"/>Proponer relación</Button></div></section>
    {message&&<Card className="shadow-none"><CardContent className="p-4 text-sm">{message}</CardContent></Card>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Líneas',counts?.total||0],['Aprobadas',counts?.approved||0],['Propuestas',counts?.proposed||0],['Equipos cubiertos',counts?.assets||0],['Repuestos usados',counts?.products||0]].map(([l,v])=><Card key={String(l)} className="shadow-none"><CardContent className="p-4"><p className="text-2xl font-semibold">{Number(v).toLocaleString('es-CL')}</p><p className="mt-1 text-xs text-muted-foreground">{l}</p></CardContent></Card>)}</div>
    {showForm&&<Card className="shadow-none"><CardHeader><CardTitle className="text-lg">Nueva relación BOM</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Código exacto del equipo</Label><Input value={form.assetCode} onChange={e=>setForm({...form,assetCode:e.target.value})}/></div><div className="space-y-2"><Label>Código exacto del repuesto</Label><Input value={form.productCode} onChange={e=>setForm({...form,productCode:e.target.value})}/></div><div className="space-y-2"><Label>Código de componente</Label><Input value={form.componentCode} onChange={e=>setForm({...form,componentCode:e.target.value})}/></div><div className="space-y-2"><Label>Componente</Label><Input value={form.componentName} onChange={e=>setForm({...form,componentName:e.target.value})}/></div><div className="space-y-2"><Label>Ruta técnica</Label><Input placeholder="Motor > Lubricación > Filtro" value={form.componentPath} onChange={e=>setForm({...form,componentPath:e.target.value})}/></div><div className="space-y-2"><Label>Cantidad requerida</Label><Input type="number" min="0.001" step="0.001" value={form.quantityRequired} onChange={e=>setForm({...form,quantityRequired:e.target.value})}/></div><div className="space-y-2 md:col-span-2"><Label>Fundamento</Label><Textarea rows={3} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Manual, ficha técnica, verificación en terreno u otra evidencia."/></div><div className="space-y-2 md:col-span-2"><Label>Evidencia</Label><Input value={form.evidenceReference} onChange={e=>setForm({...form,evidenceReference:e.target.value})} placeholder="Documento, folio, URL o referencia verificable"/></div><div className="md:col-span-2 flex gap-2"><Button disabled={saving}>Guardar propuesta</Button><Button type="button" variant="ghost" onClick={()=>setShowForm(false)}>Cancelar</Button></div></form></CardContent></Card>}
    <Card className="shadow-none"><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_220px]"><Input placeholder="Buscar equipo, componente o repuesto" value={query} onChange={e=>setQuery(e.target.value)}/><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos los estados</SelectItem><SelectItem value="approved">Aprobadas</SelectItem><SelectItem value="proposed">Propuestas</SelectItem><SelectItem value="rejected">Rechazadas</SelectItem><SelectItem value="inactive">Inactivas</SelectItem></SelectContent></Select></CardContent></Card>
    <Card className="shadow-none"><CardHeader><CardTitle className="text-lg">Equipo → componente → repuesto · {filtered.length}</CardTitle></CardHeader><CardContent className="p-0">{error?<div className="p-6 text-sm text-muted-foreground">No se pudo cargar la BOM técnica.</div>:isLoading?<div className="p-6 text-sm text-muted-foreground">Cargando…</div>:filtered.length===0?<div className="p-8 text-center text-sm text-muted-foreground"><GitBranch className="mx-auto mb-3 h-5 w-5"/>No hay relaciones para este filtro.</div>:<div className="divide-y border-t">{filtered.slice(0,500).map(row=><div key={row.id} className="p-4"><div className="flex flex-col gap-3 xl:flex-row xl:justify-between"><div className="min-w-0"><div className="flex flex-wrap gap-2"><Badge variant={row.status==='approved'?'default':'secondary'}>{row.status==='approved'?'Aprobada':row.status==='proposed'?'Propuesta':row.status==='rejected'?'Rechazada':'Inactiva'}</Badge>{row.stock&&Number(row.stock.shortage_quantity||0)>0&&<Badge variant="destructive">Faltante</Badge>}</div><p className="mt-3 font-medium">{row.asset?.asset_code||'Equipo'} · {row.asset?.name||'Sin nombre'}</p><p className="mt-1 text-sm">{row.component_path||row.component_name}{row.component_code?` · ${row.component_code}`:''}</p><p className="mt-1 text-sm font-medium">{row.product?.product_code||'Producto'} · {row.product?.name||'Sin nombre'} · {Number(row.quantity_required).toLocaleString('es-CL')} {row.product?.unit||''}</p><p className="mt-2 text-xs text-muted-foreground">OT con requerimiento: {row.operational?.work_order_requirements||0} · Instalado registrado: {Number(row.operational?.installed_quantity||0).toLocaleString('es-CL')} · Preventivos del equipo: {row.operational?.equipment_preventives||0} · Campañas del equipo: {row.operational?.equipment_campaigns||0}</p><p className="mt-1 text-xs text-muted-foreground">Stock canónico: {row.stock?Number(row.stock.quantity_available||0).toLocaleString('es-CL'):'Sin dato'} · Fundamento: {row.reason}</p></div><div className="flex shrink-0 flex-wrap gap-2"><Button size="sm" variant="outline" asChild><a href={`/dashboard/mantenimiento/equipos/${row.asset?.id}`}><ExternalLink className="mr-2 h-4 w-4"/>Equipo</a></Button>{row.product?.id&&<Button size="sm" variant="outline" asChild><a href={`/dashboard/bodega/productos-360?productId=${row.product.id}`}><PackageSearch className="mr-2 h-4 w-4"/>Producto</a></Button>}{row.status==='proposed'&&<><Button size="sm" onClick={()=>void changeStatus(row.id,'approved')}><CheckCircle2 className="mr-2 h-4 w-4"/>Aprobar</Button><Button size="sm" variant="outline" onClick={()=>void changeStatus(row.id,'rejected')}><XCircle className="mr-2 h-4 w-4"/>Rechazar</Button></>}</div></div></div>)}</div>}</CardContent></Card>
    <Card className="shadow-none"><CardHeader><CardTitle className="text-lg">Dónde se usa</CardTitle></CardHeader><CardContent>{(data?.whereUsed||[]).length===0?<p className="text-sm text-muted-foreground">Aún no hay relaciones aprobadas para construir trazabilidad de uso.</p>:<div className="space-y-4">{data!.whereUsed.map((row:any)=><div key={row.product.id} className="rounded-lg border p-4"><p className="font-medium">{row.product.product_code} · {row.product.name}</p><p className="mt-1 text-sm text-muted-foreground">{row.assets.length} ubicación{row.assets.length===1?'':'es'} técnica{row.assets.length===1?'':'s'} aprobada{row.assets.length===1?'':'s'}</p><div className="mt-3 space-y-1 text-sm">{row.assets.map((a:any,i:number)=><p key={`${a.asset?.id}-${i}`}>{a.asset?.asset_code||'Equipo'} · {a.asset?.name||'Sin nombre'} → {a.component_name}{a.component_code?` (${a.component_code})`:''}</p>)}</div></div>)}</div>}</CardContent></Card>
  </div>;
}
