'use client';

import Link from 'next/link';
import useSWR from 'swr';
import { useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, DollarSign, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

const fetcher = (url: string) => fetch(url).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data?.error || 'Error'); return data; });
const labels: Record<string, string> = { maintain: 'Mantener', repair: 'Reparar', rebuild: 'Reconstruir', replace: 'Reemplazar', retire: 'Retirar' };

export default function AssetLifecyclePage() {
  const { data, error, mutate, isLoading } = useSWR('/api/maintenance/asset-lifecycle', fetcher);
  const [form, setForm] = useState({ assetCode: '', decisionType: 'maintain', reason: '', evidenceReference: '', targetDate: '' });
  const items = useMemo(() => data?.items || [], [data]);
  async function submit() { const response = await fetch('/api/maintenance/asset-lifecycle', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) throw new Error(result?.error || 'No se pudo guardar'); setForm({ assetCode: '', decisionType: 'maintain', reason: '', evidenceReference: '', targetDate: '' }); await mutate(); }
  async function change(id: string, status: string) { await fetch('/api/maintenance/asset-lifecycle', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status }) }); await mutate(); }

  return <div className="space-y-6 p-6">
    <div className="flex flex-col items-start justify-between gap-4 md:flex-row"><div><h1 className="text-2xl font-semibold">Ciclo de vida de activos</h1><p className="text-sm text-muted-foreground">Decisiones trazables de mantener, reparar, reconstruir, reemplazar o retirar, basadas en evidencia registrada.</p></div><div className="flex gap-2"><Button asChild variant="outline"><Link href="/dashboard/mantenimiento/inversion-renovacion"><DollarSign className="mr-2 h-4 w-4" />Planificar inversión</Link></Button><Button variant="outline" onClick={() => mutate()}><RefreshCw className="mr-2 h-4 w-4" />Actualizar</Button></div></div>
    <div className="grid gap-3 md:grid-cols-4">{[['Activos', data?.counts?.assets], ['Decisión aprobada', data?.counts?.withApprovedDecision], ['Reemplazar / retirar', data?.counts?.replaceOrRetire], ['Con brechas de evidencia', data?.counts?.withEvidenceGaps]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value ?? '—'}</p></CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle className="text-base">Proponer decisión</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-5"><Input placeholder="Código equipo" value={form.assetCode} onChange={(e) => setForm({ ...form, assetCode: e.target.value })}/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={form.decisionType} onChange={(e) => setForm({ ...form, decisionType: e.target.value })}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Input placeholder="Fundamento" value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })}/><Input placeholder="Referencia de evidencia" value={form.evidenceReference} onChange={(e) => setForm({ ...form, evidenceReference: e.target.value })}/><div className="flex gap-2"><Input type="date" value={form.targetDate} onChange={(e) => setForm({ ...form, targetDate: e.target.value })}/><Button onClick={() => submit().catch((err) => alert(err.message))}>Proponer</Button></div></CardContent></Card>
    {error ? <p className="text-sm text-destructive">{error.message}</p> : null}{isLoading ? <p className="text-sm text-muted-foreground">Cargando evidencia…</p> : null}
    <div className="grid gap-4 xl:grid-cols-2">{items.map((row: any) => <Card key={row.asset.id}><CardHeader className="pb-3"><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-base">{row.asset.asset_code} · {row.asset.name}</CardTitle><p className="text-xs text-muted-foreground">{row.asset.manufacturer || '—'} {row.asset.model || ''}</p></div>{row.decision ? <span className="rounded-full border px-2 py-1 text-xs">{labels[row.decision.decision_type] || row.decision.decision_type} · {row.decision.status}</span> : null}</div></CardHeader><CardContent className="space-y-3"><div className="grid grid-cols-2 gap-2 text-xs md:grid-cols-4"><span>OT: <b>{row.evidence.workOrders}</b></span><span>Correctivas: <b>{row.evidence.correctiveWorkOrders}</b></span><span>Downtime: <b>{row.evidence.totalDowntimeHours}</b> h</span><span>Costo mant.: <b>{Number(row.evidence.totalMaintenanceCost || 0).toLocaleString('es-CL')}</b></span><span>Preventivos: <b>{row.evidence.activePreventives}</b></span><span>Repuestos instalados: <b>{row.evidence.installedPartLines}</b></span><span>Adquisición: <b>{row.evidence.acquisitionDate || 'sin dato'}</b></span><span>Criticidad: <b>{row.evidence.criticality || 'sin clasificar'}</b></span></div>{row.gaps.length ? <div className="rounded-lg border border-amber-300/50 bg-amber-50/40 p-3 text-xs dark:bg-amber-950/10"><div className="mb-1 flex items-center gap-2 font-medium"><AlertTriangle className="h-4 w-4" />Brechas de evidencia</div>{row.gaps.map((gap: string) => <div key={gap}>• {gap}</div>)}</div> : <div className="flex items-center gap-2 text-xs text-emerald-700"><CheckCircle2 className="h-4 w-4" />Evidencia base disponible</div>}{row.decision?.status === 'proposed' ? <Button size="sm" onClick={() => change(row.decision.id, 'approved')}>Aprobar</Button> : null}{row.decision?.status === 'approved' ? <Button size="sm" variant="outline" onClick={() => change(row.decision.id, 'inactive')}>Inactivar</Button> : null}</CardContent></Card>)}</div>
  </div>;
}
