'use client';

import { FormEvent, useMemo, useState } from 'react';
import useSWR from 'swr';
import { AlertTriangle, CheckCircle2, Plus, RefreshCw, ShieldCheck } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

type Strategy = { id:string; criticality_level:string; maintenance_strategy:string; status:string; reason:string; evidence_reference:string|null };
type Item = { asset:{id:string;asset_code:string;name:string;asset_type:string|null;category:string|null;manufacturer:string|null;model:string|null}; strategy:Strategy|null; coverage:{preventive:number;approvedBomLines:number;criticalSpareLinks:number;approvedStandardPlans:number;telemetryLinked:boolean}; gaps:string[] };
type Data = { counts:{assets:number;classified:number;critical:number;high:number;withGaps:number}; items:Item[]; generatedAt:string };
const fetcher=async(url:string)=>{const r=await fetch(url,{credentials:'include',cache:'no-store'});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||'No se pudo cargar');return p as Data;};
const criticalityLabels:Record<string,string>={critical:'Crítica',high:'Alta',medium:'Media',low:'Baja'};
const strategyLabels:Record<string,string>={preventive:'Preventiva',predictive:'Predictiva',inspection:'Inspección',run_to_failure:'Run-to-failure'};

export default function MaintenanceStrategyPage(){
 const {data,error,isLoading,isValidating,mutate}=useSWR('/api/maintenance/asset-strategies',fetcher,{revalidateOnFocus:false});
 const [query,setQuery]=useState(''); const [showForm,setShowForm]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
 const [form,setForm]=useState({assetCode:'',criticalityLevel:'high',maintenanceStrategy:'preventive',reason:'',evidenceReference:''});
 const filtered=useMemo(()=> (data?.items||[]).filter(row=>!query.trim()||`${row.asset.asset_code} ${row.asset.name} ${row.asset.asset_type||''} ${row.strategy?.criticality_level||''} ${row.strategy?.maintenance_strategy||''}`.toLowerCase().includes(query.toLowerCase())),[data?.items,query]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage(null);const r=await fetch('/api/maintenance/asset-strategies',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const p=await r.json().catch(()=>null);setSaving(false);if(!r.ok){setMessage(p?.error||'No se pudo guardar.');return;}setMessage('Clasificación propuesta. Debe aprobarse antes de considerarse vigente.');setShowForm(false);await mutate();}
 async function changeStatus(id:string,status:string){const r=await fetch('/api/maintenance/asset-strategies',{method:'PATCH',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});const p=await r.json().catch(()=>null);if(!r.ok){setMessage(p?.error||'No se pudo actualizar.');return;}setMessage(status==='approved'?'Estrategia aprobada. Las brechas se recalcularon con datos operacionales vigentes.':'Estrategia actualizada.');await mutate();}
 const c=data?.counts;
 return <div className="space-y-6">
  <section className="flex flex-col gap-4 border-b border-border/70 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-medium text-muted-foreground">Mantenimiento · Estrategia</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Criticidad y estrategia de activos</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Registra una decisión explícita por equipo y verifica su cobertura real. Motil muestra brechas observables; no asigna criticidad ni recomienda estrategias automáticamente.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void mutate()} disabled={isValidating}><RefreshCw className={`mr-2 h-4 w-4 ${isValidating?'animate-spin':''}`}/>Actualizar</Button><Button onClick={()=>setShowForm(v=>!v)}><Plus className="mr-2 h-4 w-4"/>Proponer estrategia</Button></div></section>
  {message&&<Card className="shadow-none"><CardContent className="p-4 text-sm">{message}</CardContent></Card>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Activos',c?.assets||0],['Clasificados',c?.classified||0],['Críticos',c?.critical||0],['Alta criticidad',c?.high||0],['Con brechas',c?.withGaps||0]].map(([l,v])=><Card key={String(l)} className="shadow-none"><CardContent className="p-4"><p className="text-2xl font-semibold">{Number(v).toLocaleString('es-CL')}</p><p className="mt-1 text-xs text-muted-foreground">{l}</p></CardContent></Card>)}</div>
  {showForm&&<Card className="shadow-none"><CardHeader><CardTitle className="text-lg">Nueva propuesta de estrategia</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Código de equipo</Label><Input placeholder="Código canónico exacto" value={form.assetCode} onChange={e=>setForm({...form,assetCode:e.target.value})}/></div><div className="space-y-2"><Label>Criticidad</Label><Select value={form.criticalityLevel} onValueChange={v=>setForm({...form,criticalityLevel:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="critical">Crítica</SelectItem><SelectItem value="high">Alta</SelectItem><SelectItem value="medium">Media</SelectItem><SelectItem value="low">Baja</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Estrategia</Label><Select value={form.maintenanceStrategy} onValueChange={v=>setForm({...form,maintenanceStrategy:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="preventive">Preventiva</SelectItem><SelectItem value="predictive">Predictiva</SelectItem><SelectItem value="inspection">Inspección</SelectItem><SelectItem value="run_to_failure">Run-to-failure</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Evidencia o referencia</Label><Input value={form.evidenceReference} onChange={e=>setForm({...form,evidenceReference:e.target.value})}/></div><div className="space-y-2 md:col-span-2"><Label>Fundamento de la decisión</Label><Textarea rows={3} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></div><div className="md:col-span-2 flex gap-2"><Button disabled={saving}>Guardar propuesta</Button><Button type="button" variant="ghost" onClick={()=>setShowForm(false)}>Cancelar</Button></div></form></CardContent></Card>}
  <Input placeholder="Buscar equipo, criticidad o estrategia" value={query} onChange={e=>setQuery(e.target.value)}/>
  <Card className="shadow-none"><CardHeader><CardTitle className="text-lg">Activos · {filtered.length}</CardTitle></CardHeader><CardContent className="p-0">{error?<div className="p-6 text-sm text-muted-foreground">No se pudo cargar la estrategia de mantenimiento.</div>:isLoading?<div className="p-6 text-sm text-muted-foreground">Cargando…</div>:filtered.length===0?<div className="p-8 text-center text-sm text-muted-foreground"><ShieldCheck className="mx-auto mb-3 h-5 w-5"/>No hay activos disponibles.</div>:<div className="divide-y border-t">{filtered.map(row=><div key={row.asset.id} className="p-4"><div className="flex flex-col gap-4 xl:flex-row xl:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2">{row.strategy?<><Badge variant={row.strategy.status==='approved'?'default':'secondary'}>{row.strategy.status==='approved'?'Aprobada':'Propuesta'}</Badge><Badge variant="outline">{criticalityLabels[row.strategy.criticality_level]||row.strategy.criticality_level}</Badge><Badge variant="outline">{strategyLabels[row.strategy.maintenance_strategy]||row.strategy.maintenance_strategy}</Badge></>:<Badge variant="secondary">Sin clasificación</Badge>}{row.gaps.length>0&&<Badge variant="destructive"><AlertTriangle className="mr-1 h-3 w-3"/>{row.gaps.length} brecha(s)</Badge>}</div><p className="mt-3 font-medium">{row.asset.asset_code} · {row.asset.name}</p><p className="mt-1 text-xs text-muted-foreground">{[row.asset.asset_type,row.asset.manufacturer,row.asset.model].filter(Boolean).join(' · ')||'Sin detalle técnico adicional'}</p>{row.strategy&&<p className="mt-2 text-sm">Fundamento: {row.strategy.reason}</p>}<div className="mt-3 flex flex-wrap gap-2 text-xs"><Badge variant="outline">Preventivos: {row.coverage.preventive}</Badge><Badge variant="outline">BOM aprobada: {row.coverage.approvedBomLines}</Badge><Badge variant="outline">Repuestos críticos vinculados: {row.coverage.criticalSpareLinks}</Badge><Badge variant="outline">Planes estándar: {row.coverage.approvedStandardPlans}</Badge><Badge variant="outline">Telemetría: {row.coverage.telemetryLinked?'Sí':'No'}</Badge></div>{row.gaps.length>0&&<div className="mt-3 space-y-1 text-sm text-destructive">{row.gaps.map(g=><p key={g}>• {g}</p>)}</div>}</div><div className="shrink-0 flex gap-2">{row.strategy?.status==='proposed'&&<Button size="sm" onClick={()=>void changeStatus(row.strategy!.id,'approved')}><CheckCircle2 className="mr-2 h-4 w-4"/>Aprobar</Button>}{row.strategy?.status==='approved'&&<Button size="sm" variant="outline" onClick={()=>void changeStatus(row.strategy!.id,'inactive')}>Inactivar</Button>}</div></div></div>)}</div>}</CardContent></Card>
  <p className="text-xs text-muted-foreground">Las brechas solo se calculan para estrategias aprobadas de criticidad crítica o alta. La ausencia de datos se muestra como ausencia; no se reemplaza con estimaciones.</p>
 </div>;
}