'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import useSWR from 'swr';
import { AlertTriangle, CheckCircle2, PauseCircle, PlayCircle, Plus, RefreshCw, Wrench } from 'lucide-react';
import { apiFetch } from '@/lib/api-client';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { StatePanel } from '@/components/ui/state-panel';

type Asset = { id: string; asset_code: string; asset_name: string; asset_type?: string | null; location?: string | null };
type Schedule = { id: string; asset_id: string; task_name: string; description?: string | null; frequency_days?: number | null; frequency_hours?: number | null; next_scheduled_date?: string | null; estimated_duration_hours?: number | null; priority?: string | null; enabled: boolean; generated_work_order_id?: string | null; asset?: Asset | null };
type OpenWorkOrder = { id: string; work_order_number: string; title: string; status: string };
type OperationCandidate = { canonical_asset_id: string; rig_name: string; suggested_task: string; observation_count: number; out_of_service_count: number; first_observed_at: string; last_observed_at: string; latest_observation?: string | null; signal_status: string; latest_source_file?: string | null; latest_source_sheet?: string | null; latest_source_row?: number | null; open_work_orders: OpenWorkOrder[]; promotion_state: string };
type HourSignal = { schedule_id: string; asset_code: string; asset_name: string; task_name: string; frequency_hours?: number | null; last_executed_meter?: number | null; due_meter?: number | null; effective_current_meter?: number | null; remaining_hours?: number | null; hour_status: string; alert_due: boolean; meter_evidence_source?: string | null; meter_basis_warning: boolean; evidence_quality: string; source_reference?: string | null; generated_work_order_id?: string | null };
type Response = { schedules: Schedule[]; assets: Asset[]; summary: { total: number; overdue: number; dueSoon: number; disabled: number; generated: number }; operationCandidates: OperationCandidate[]; hourSignals: HourSignal[]; intelligenceSummary: { operationCandidates: number; attentionCandidates: number; hourAlerts: number; hourEvidenceWarnings: number } };

const fetcher = async (url: string): Promise<Response> => { const response = await apiFetch(url); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error || 'No se pudo cargar la planificación preventiva.'); return payload as Response; };
function dueState(date?: string | null) { if (!date) return { label: 'Sin fecha', tone: 'secondary' as const }; const today = new Date(); today.setHours(0, 0, 0, 0); const due = new Date(`${date}T00:00:00`); const days = Math.ceil((due.getTime() - today.getTime()) / 86400000); if (days < 0) return { label: `Vencida hace ${Math.abs(days)} días`, tone: 'destructive' as const }; if (days === 0) return { label: 'Vence hoy', tone: 'destructive' as const }; if (days <= 30) return { label: `Vence en ${days} días`, tone: 'default' as const }; return { label: date, tone: 'secondary' as const }; }
const numberOrDash = (value?: number | null) => value == null ? '—' : Number(value).toLocaleString('es-CL', { maximumFractionDigits: 1 });

export function PreventivePlanBoard() {
  const { data, error, isLoading, mutate } = useSWR<Response>('/api/maintenance/preventive', fetcher, { revalidateOnFocus: false });
  const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const [form, setForm] = useState({ assetId: '', taskName: '', description: '', frequencyDays: '', frequencyHours: '', nextScheduledDate: '', estimatedDurationHours: '', priority: 'medium' });
  const schedules = data?.schedules || []; const summary = data?.summary || null;
  const ordered = useMemo(() => [...schedules].sort((a, b) => String(a.next_scheduled_date || '9999').localeCompare(String(b.next_scheduled_date || '9999'))), [schedules]);
  const candidates = useMemo(() => [...(data?.operationCandidates || [])].sort((a, b) => (b.signal_status === 'attention' ? 1 : 0) - (a.signal_status === 'attention' ? 1 : 0) || b.out_of_service_count - a.out_of_service_count || b.observation_count - a.observation_count).slice(0, 8), [data?.operationCandidates]);
  const hourSignals = useMemo(() => [...(data?.hourSignals || [])].filter((item) => item.alert_due || item.meter_basis_warning).slice(0, 8), [data?.hourSignals]);
  const metricValue = (value: number | undefined) => isLoading || error || !summary || value == null ? '—' : value.toLocaleString('es-CL');

  function promoteCandidate(candidate: OperationCandidate) { setForm({ assetId: candidate.canonical_asset_id, taskName: candidate.suggested_task, description: `Candidato derivado de ${candidate.observation_count} observaciones operacionales entre ${candidate.first_observed_at} y ${candidate.last_observed_at}. Requiere validación del supervisor antes de generar trabajo.`, frequencyDays: '', frequencyHours: '', nextScheduledDate: '', estimatedDurationHours: '', priority: candidate.signal_status === 'attention' ? 'high' : 'medium' }); setShowForm(true); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function submit() { setSaving(true); setMessage(''); try { const response = await apiFetch('/api/maintenance/preventive', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error || 'No se pudo crear el plan.'); setForm({ assetId: '', taskName: '', description: '', frequencyDays: '', frequencyHours: '', nextScheduledDate: '', estimatedDurationHours: '', priority: 'medium' }); setShowForm(false); setMessage('Plan preventivo creado.'); await mutate(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'No se pudo crear el plan.'); } finally { setSaving(false); } }
  async function act(scheduleId: string, action: 'toggle' | 'generate') { setMessage(''); try { const response = await apiFetch('/api/maintenance/preventive', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scheduleId, action }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error || 'No se pudo actualizar el plan.'); setMessage(action === 'generate' ? 'Orden de trabajo creada desde el plan.' : 'Estado actualizado.'); await mutate(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'No se pudo actualizar el plan.'); } }

  return <main className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b pb-5"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Mantenimiento</p><h1 className="mt-1 text-2xl font-semibold">Planificación preventiva</h1><p className="mt-1 text-sm text-muted-foreground">Planes canónicos, señales operacionales y vencimientos por horas. La evidencia derivada requiere revisión humana.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void mutate()} disabled={isLoading}><RefreshCw className="h-4 w-4"/>Actualizar</Button><Button onClick={() => setShowForm((value) => !value)} disabled={isLoading || Boolean(error)}><Plus className="h-4 w-4"/>Nuevo plan</Button></div></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['Planes', metricValue(summary?.total)], ['Vencidos', metricValue(summary?.overdue)], ['Próximos 30 días', metricValue(summary?.dueSoon)], ['Pausados', metricValue(summary?.disabled)], ['OT generadas', metricValue(summary?.generated)]].map(([label, value]) => <Card key={String(label)} className="shadow-none"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></CardContent></Card>)}</section>

    {showForm && <Card className="shadow-none"><CardHeader><CardTitle className="text-base">Nuevo plan preventivo</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Select value={form.assetId} onValueChange={(value) => setForm({ ...form, assetId: value })}><SelectTrigger><SelectValue placeholder="Equipo"/></SelectTrigger><SelectContent>{(data?.assets || []).map((asset) => <SelectItem key={asset.id} value={asset.id}>{asset.asset_code} · {asset.asset_name}</SelectItem>)}</SelectContent></Select><Input placeholder="Tarea" value={form.taskName} onChange={(e) => setForm({ ...form, taskName: e.target.value })}/><Input type="date" value={form.nextScheduledDate} onChange={(e) => setForm({ ...form, nextScheduledDate: e.target.value })}/><Select value={form.priority} onValueChange={(value) => setForm({ ...form, priority: value })}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="low">Baja</SelectItem><SelectItem value="medium">Media</SelectItem><SelectItem value="high">Alta</SelectItem><SelectItem value="critical">Crítica</SelectItem></SelectContent></Select><Input type="number" min="1" placeholder="Frecuencia en días" value={form.frequencyDays} onChange={(e) => setForm({ ...form, frequencyDays: e.target.value })}/><Input type="number" min="1" placeholder="Frecuencia en horas" value={form.frequencyHours} onChange={(e) => setForm({ ...form, frequencyHours: e.target.value })}/><Input type="number" min="0" step="0.5" placeholder="Duración estimada" value={form.estimatedDurationHours} onChange={(e) => setForm({ ...form, estimatedDurationHours: e.target.value })}/><Input placeholder="Descripción" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/><div className="md:col-span-2 xl:col-span-4 flex justify-end gap-2"><Button variant="outline" onClick={() => setShowForm(false)}>Cancelar</Button><Button disabled={saving} onClick={() => void submit()}>{saving ? 'Guardando…' : 'Guardar plan'}</Button></div></CardContent></Card>}
    {message && <p className="rounded-lg border p-3 text-sm">{message}</p>}
    {error ? <StatePanel tone="error" title="Planificación preventiva no disponible" description={error.message} actions={<Button variant="outline" onClick={() => void mutate()}>Reintentar</Button>} className="min-h-0" /> : null}

    {!isLoading && !error && (candidates.length > 0 || hourSignals.length > 0) && <section className="space-y-3"><div><h2 className="text-lg font-semibold">Qué requiere atención</h2><p className="text-sm text-muted-foreground">Señales derivadas de operación y horómetros. No son diagnóstico ni OT hasta validación humana.</p></div><div className="grid gap-3 xl:grid-cols-2">
      {candidates.length > 0 && <Card className="shadow-none"><CardHeader><CardTitle className="text-base">Tareas sugeridas desde operación</CardTitle></CardHeader><CardContent className="space-y-3">{candidates.map((candidate) => <div key={`${candidate.canonical_asset_id}-${candidate.suggested_task}`} className="border-b pb-3 last:border-0 last:pb-0"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="flex flex-wrap gap-2"><Badge variant={candidate.signal_status === 'attention' ? 'destructive' : 'secondary'}>{candidate.signal_status === 'attention' ? 'Atención' : 'Recurrente'}</Badge><Badge variant="outline">Derivado</Badge></div><p className="mt-2 font-medium">{candidate.suggested_task}</p><p className="text-sm text-muted-foreground">{candidate.rig_name} · {candidate.observation_count} observaciones · {candidate.out_of_service_count} fuera de servicio</p></div><Button size="sm" variant="outline" onClick={() => promoteCandidate(candidate)}>Revisar como plan</Button></div>{candidate.latest_observation && <p className="mt-2 text-sm">Última evidencia: {candidate.latest_observation}</p>}{candidate.open_work_orders.length > 0 && <p className="mt-1 text-xs text-muted-foreground">Este equipo ya tiene {candidate.open_work_orders.length} OT abierta(s). Revisar antes de crear trabajo adicional.</p>}<p className="mt-1 text-xs text-muted-foreground">Fuente: {candidate.latest_source_file || 'reporte operacional'} · última observación {candidate.last_observed_at}</p></div>)}</CardContent></Card>}
      {hourSignals.length > 0 && <Card className="shadow-none"><CardHeader><CardTitle className="text-base">Control por horómetro</CardTitle></CardHeader><CardContent className="space-y-3">{hourSignals.map((signal) => <div key={signal.schedule_id} className="border-b pb-3 last:border-0 last:pb-0"><div className="flex flex-wrap gap-2">{signal.meter_basis_warning ? <Badge variant="destructive"><AlertTriangle className="mr-1 h-3 w-3"/>Reconciliar contador</Badge> : signal.alert_due ? <Badge variant="destructive">Vencido por horas</Badge> : <Badge variant="secondary">Por revisar</Badge>}<Badge variant="outline">{signal.evidence_quality === 'observed_runtime' ? 'Lectura observada' : 'Snapshot de fuente'}</Badge></div><p className="mt-2 font-medium">{signal.task_name}</p><p className="text-sm text-muted-foreground">{signal.asset_code} · {signal.asset_name}</p><div className="mt-2 grid grid-cols-3 gap-2 text-sm"><div><p className="text-xs text-muted-foreground">Actual</p><p>{numberOrDash(signal.effective_current_meter)} h</p></div><div><p className="text-xs text-muted-foreground">Objetivo</p><p>{numberOrDash(signal.due_meter)} h</p></div><div><p className="text-xs text-muted-foreground">Restante</p><p>{numberOrDash(signal.remaining_hours)} h</p></div></div>{signal.meter_basis_warning && <p className="mt-2 text-xs text-muted-foreground">El contador de la fuente es menor que la última ejecución registrada. No se usa como base confiable hasta reconciliar reset, cambio de contador o error de planilla.</p>}</div>)}</CardContent></Card>}
    </div></section>}

    <section className="space-y-3"><div><h2 className="text-lg font-semibold">Planes preventivos</h2><p className="text-sm text-muted-foreground">Programación aprobada y generación controlada de órdenes.</p></div>{isLoading ? <div className="h-40 animate-pulse rounded-lg bg-muted"/> : error ? null : ordered.length === 0 ? <Card className="border-dashed shadow-none"><CardContent className="p-10 text-center text-sm text-muted-foreground">No existen planes preventivos registrados. Crea el primero desde “Nuevo plan”.</CardContent></Card> : <div className="space-y-3">{ordered.map((schedule) => { const state = dueState(schedule.next_scheduled_date); return <Card key={schedule.id} className="shadow-none"><CardContent className="grid gap-4 p-4 lg:grid-cols-[minmax(0,1fr)_180px_170px_auto] lg:items-center"><div><div className="flex flex-wrap gap-2"><Badge variant={state.tone}>{state.label}</Badge><Badge variant="outline">{schedule.priority || 'Sin prioridad'}</Badge>{!schedule.enabled && <Badge variant="secondary">Pausado</Badge>}</div><p className="mt-2 font-medium">{schedule.task_name}</p><p className="text-sm text-muted-foreground">{schedule.asset?.asset_code || 'Sin código'} · {schedule.asset?.asset_name || 'Equipo no disponible'}</p>{schedule.description && <p className="mt-1 text-sm text-muted-foreground">{schedule.description}</p>}</div><div><p className="text-xs text-muted-foreground">Frecuencia</p><p className="text-sm">{schedule.frequency_days ? `Cada ${schedule.frequency_days} días` : schedule.frequency_hours ? `Cada ${schedule.frequency_hours} horas` : 'No definida'}</p></div><div><p className="text-xs text-muted-foreground">Orden relacionada</p>{schedule.generated_work_order_id ? <Button asChild variant="link" className="h-auto p-0"><Link href={`/dashboard/mantenimiento/ordenes-trabajo/${schedule.generated_work_order_id}`}><CheckCircle2 className="h-4 w-4"/>Abrir OT</Link></Button> : <p className="text-sm text-muted-foreground">Aún no generada</p>}</div><div className="flex flex-wrap justify-end gap-2"><Button size="sm" variant="outline" onClick={() => void act(schedule.id, 'toggle')}>{schedule.enabled ? <PauseCircle className="h-4 w-4"/> : <PlayCircle className="h-4 w-4"/>}{schedule.enabled ? 'Pausar' : 'Activar'}</Button><Button size="sm" disabled={!schedule.enabled || Boolean(schedule.generated_work_order_id)} onClick={() => void act(schedule.id, 'generate')}><Wrench className="h-4 w-4"/>Crear OT</Button></div></CardContent></Card>; })}</div>}</section>
  </main>;
}
