'use client';

import useSWR from 'swr';
import { Activity, AlertTriangle, Factory, Gauge, Layers3, Scale } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageHeader, PageHeaderContent, PageHeaderDescription, PageHeaderEyebrow, PageHeaderTitle } from '@/components/ui/page-header';
import { StatePanel } from '@/components/ui/state-panel';

type Row = { plant_shift_id:string; operation_date:string; shift_code:string|null; treated_metric_tons:number|null; mineral_moisture_pct:number|null; head_grade:number|null; concentrate_grade:number|null; tailings_grade:number|null; recovery_reported:number|null; recovery_by_grades_pct:number|null; metallurgy_state:string; source_file:string|null; source_row:number|null };
type Data = {
  period:null|{periodStart:string;dataThrough:string;shifts:number;movements:number;transportedTons:number;treatedTons:number;transportTreatmentDeltaTons:number;flowReconciliationState:string;dryTons:number;mineralMoisturePct:number|null;headGradePct:number|null;concentrateGradePct:number|null;tailingsGradePct:number|null;recoveryPct:number|null;recoveredFineCuTons:number;containedFeedCuTons:number;containedCuPlanProgressPct:number|null;wetTonsWithoutFine:number;fineCoverageState:string;fineRuleVersion:string;fineMetalReportedTons:number;concentrateWetTons:number;assayed:number;partial:number;noAssay:number;assayCoveragePct:number};
  plan:null|{plan_code:string;period_start:string;period_end:string;total_mineral_to_plant_tons:number|null;target_cu_grade_pct:number|null;plannedContainedCuTons:number|null;containedCuPlanState:string;plannedFineSemantic:string;sourceReference:string;targetRecoveryPct:number|null;plannedRecoveredFineCuTons:null;recoveredFinePlanState:string};
  daily:Array<{operationDate:string;shifts:number;movements:number;transportedTons:number|null;treatedTons:number;transportTreatmentDeltaTons:number|null;flowState:string;headGradePct:number|null;concentrateGradePct:number|null;tailingsGradePct:number|null;recoveryPct:number|null;containedCuTons:number|null;fineCuTons:number|null;fineCoverageState:string;assayed:number;noAssay:number}>;
  recent:Row[];
  historical:null|{rows:number;minDate:string|null;maxDate:string;assayed:number;partial:number;noAssay:number};
  lineage:{source:string;model:string;note:string};
};
const fetcher=async(url:string):Promise<Data>=>{const r=await fetch(url,{credentials:'include'});const d=await r.json();if(!r.ok)throw new Error(d.error||'No fue posible cargar Planta / Metalurgia');return d};
const pct=(v:number|null|undefined,d=2)=>v==null?'—':`${v.toLocaleString('es-CL',{maximumFractionDigits:d})}%`;
const tons=(v:number|null|undefined,d=1)=>`${Number(v||0).toLocaleString('es-CL',{maximumFractionDigits:d})} t`;
const signedTons=(v:number|null|undefined,d=1)=>v==null?'—':`${v>0?'+':''}${v.toLocaleString('es-CL',{maximumFractionDigits:d})} t`;
const date=(v:string|null|undefined)=>v?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium'}).format(new Date(`${v}T12:00:00`)):'—';

export function PlantMetallurgyDashboard(){
  const {data,error,isLoading,mutate}=useSWR('/api/produccion/planta-metalurgia',fetcher);
  const p=data?.period;
  const metrics=[
    {label:'Mineral tratado',value:p?tons(p.treatedTons):'—',detail:`${p?.shifts??0} turnos`,icon:Factory},
    {label:'Ley cabeza Cu',value:pct(p?.headGradePct,3),detail:'Ponderada sobre mineral seco',icon:Gauge},
    {label:'Recuperación',value:pct(p?.recoveryPct,2),detail:'Balance Cu contenido → fino',icon:Activity},
    {label:'Fino Cu real',value:p?tons(p.recoveredFineCuTons,3):'—',detail:'Sólo turnos con ensayo',icon:Scale},
    {label:'Cobertura fino',value:pct(p?.assayCoveragePct,1),detail:p?.fineCoverageState==='complete'?'Completa':'Con brechas analíticas',icon:Layers3},
  ];
  return <div className="space-y-6">
    <PageHeader><PageHeaderContent><PageHeaderEyebrow>Producción · Planta</PageHeaderEyebrow><PageHeaderTitle>Producción fino</PageHeaderTitle><PageHeaderDescription>{p?`Acumulado ${date(p.periodStart)} – ${date(p.dataThrough)}. Flujo físico y cobre fino calculados sólo desde evidencia operacional.`:'Transporte, tratamiento, ley, recuperación y cobre fino por turno.'}</PageHeaderDescription></PageHeaderContent></PageHeader>
    {error?<StatePanel tone="error" title="No fue posible cargar Producción fino" description={error.message} actions={<Button variant="outline" onClick={()=>void mutate()}>Reintentar</Button>}/>:null}
    <section className="grid gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-2 xl:grid-cols-5" aria-label="Indicadores de producción fino">{metrics.map(m=>{const Icon=m.icon;return <div key={m.label} className="bg-card px-5 py-4"><div className="flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground">{m.label}</p><Icon className="h-4 w-4 text-muted-foreground"/></div><p className="mt-2 text-2xl font-semibold tracking-tight">{isLoading?'—':m.value}</p><p className="mt-1 text-xs text-muted-foreground">{m.detail}</p></div>})}</section>
    {p?<section className="rounded-lg border bg-card"><div className="border-b px-4 py-3"><div className="flex items-center gap-2"><Factory className="h-4 w-4 text-muted-foreground"/><h2 className="font-medium">Flujo físico</h2></div></div><div className="grid gap-px bg-border md:grid-cols-3"><div className="bg-card px-4 py-4"><p className="text-xs text-muted-foreground">Mineral transportado</p><p className="mt-2 text-xl font-semibold">{tons(p.transportedTons,1)}</p><p className="mt-1 text-xs text-muted-foreground">{p.movements} movimientos mina → planta</p></div><div className="bg-card px-4 py-4"><p className="text-xs text-muted-foreground">Mineral tratado</p><p className="mt-2 text-xl font-semibold">{tons(p.treatedTons,1)}</p><p className="mt-1 text-xs text-muted-foreground">Registro de planta del período</p></div><div className="bg-card px-4 py-4"><p className="text-xs text-muted-foreground">Brecha transporte − tratado</p><p className="mt-2 text-xl font-semibold">{signedTons(p.transportTreatmentDeltaTons,1)}</p><p className="mt-1 text-xs text-muted-foreground">Requiere stock/acopio para reconciliar</p></div></div></section>:null}
    {p?<section className="grid gap-px overflow-hidden rounded-lg border bg-border md:grid-cols-4"><div className="bg-card px-4 py-4"><p className="text-xs text-muted-foreground">Cu contenido real</p><p className="mt-2 text-xl font-semibold">{tons(p.containedFeedCuTons,3)}</p><p className="mt-1 text-xs text-muted-foreground">Antes de recuperación</p></div><div className="bg-card px-4 py-4"><p className="text-xs text-muted-foreground">Plan Cu contenido</p><p className="mt-2 text-xl font-semibold">{data?.plan?.plannedContainedCuTons==null?'—':tons(data.plan.plannedContainedCuTons,2)}</p><p className="mt-1 text-xs text-muted-foreground">Programa mina · pre-recuperación</p></div><div className="bg-card px-4 py-4"><p className="text-xs text-muted-foreground">Avance Cu contenido</p><p className="mt-2 text-xl font-semibold">{pct(p.containedCuPlanProgressPct,1)}</p><p className="mt-1 text-xs text-muted-foreground">Real / plan mensual comparable</p></div><div className="bg-card px-4 py-4"><p className="text-xs text-muted-foreground">Tratado sin fino calculable</p><p className="mt-2 text-xl font-semibold">{tons(p.wetTonsWithoutFine,1)}</p><p className="mt-1 text-xs text-muted-foreground">Falta ensayo / evidencia</p></div></section>:null}
    {p&&p.flowReconciliationState==='inventory_or_timing_required'?<div className="flex items-start gap-3 rounded-lg border bg-card px-4 py-3 text-sm"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground"/><div><p className="font-medium">Brecha física aún no reconciliada</p><p className="mt-1 text-muted-foreground">El período muestra {signedTons(p.transportTreatmentDeltaTons,1)} entre transporte y tratamiento. No se clasifica como pérdida: puede corresponder a stock inicial/final, acopio o desfase entre recepción y proceso.</p></div></div>:null}
    {p&&p.wetTonsWithoutFine>0?<div className="flex items-start gap-3 rounded-lg border bg-card px-4 py-3 text-sm"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground"/><div><p className="font-medium">Producción fino incompleta por falta de ensayo</p><p className="mt-1 text-muted-foreground">Hay {tons(p.wetTonsWithoutFine,1)} tratadas sin ley/recuperación suficiente para calcular fino. El sistema no estima ni reemplaza esos valores por cero.</p></div></div>:null}
    {data?.plan&&data.plan.recoveredFinePlanState==='missing_target_recovery'?<div className="flex items-start gap-3 rounded-lg border bg-card px-4 py-3 text-sm"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground"/><div><p className="font-medium">Plan de fino recuperado aún no acreditado</p><p className="mt-1 text-muted-foreground">El programa de mina entrega Cu contenido pre-recuperación, aunque lo rotula “Cu Fino Mina”. No existe recuperación objetivo documentada para convertirlo en fino recuperado de planta.</p></div></div>:null}
    {data?.daily?.length?<section className="rounded-lg border bg-card"><div className="border-b px-4 py-3"><div className="flex items-center gap-2"><Layers3 className="h-4 w-4 text-muted-foreground"/><h2 className="font-medium">Producción diaria</h2></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">Fecha</th><th className="px-4 py-3 font-medium">Transportado</th><th className="px-4 py-3 font-medium">Tratado</th><th className="px-4 py-3 font-medium">Ley cabeza</th><th className="px-4 py-3 font-medium">Cu contenido</th><th className="px-4 py-3 font-medium">Recuperación</th><th className="px-4 py-3 font-medium">Fino Cu</th></tr></thead><tbody>{data.daily.map(r=><tr key={r.operationDate} className="border-b last:border-0"><td className="px-4 py-3">{date(r.operationDate)}</td><td className="px-4 py-3">{r.transportedTons==null?'—':tons(r.transportedTons)}</td><td className="px-4 py-3">{tons(r.treatedTons)}</td><td className="px-4 py-3">{pct(r.headGradePct,3)}</td><td className="px-4 py-3">{r.containedCuTons==null?'—':tons(r.containedCuTons,3)}</td><td className="px-4 py-3">{pct(r.recoveryPct,2)}</td><td className="px-4 py-3 font-medium">{r.fineCuTons==null?'—':tons(r.fineCuTons,3)}</td></tr>)}</tbody></table></div></section>:null}
    {data?.recent?.length?<section className="rounded-lg border bg-card"><div className="border-b px-4 py-3"><h2 className="font-medium">Turnos recientes</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">Fecha</th><th className="px-4 py-3 font-medium">Turno</th><th className="px-4 py-3 font-medium">Tratado</th><th className="px-4 py-3 font-medium">Cabeza</th><th className="px-4 py-3 font-medium">Recuperación</th><th className="px-4 py-3 font-medium">Estado</th></tr></thead><tbody>{data.recent.map(r=><tr key={r.plant_shift_id} className="border-b last:border-0"><td className="px-4 py-3">{date(r.operation_date)}</td><td className="px-4 py-3">{r.shift_code||'—'}</td><td className="px-4 py-3">{tons(r.treated_metric_tons)}</td><td className="px-4 py-3">{pct(r.head_grade,3)}</td><td className="px-4 py-3">{pct(r.recovery_reported??r.recovery_by_grades_pct,2)}</td><td className="px-4 py-3">{r.metallurgy_state}</td></tr>)}</tbody></table></div></section>:null}
    {data?.lineage?<div className="rounded-lg border bg-card px-4 py-3 text-xs text-muted-foreground"><strong className="font-medium text-foreground">Linaje:</strong> {data.lineage.source}. {data.lineage.note}</div>:null}
  </div>;
}
