'use client';

import useSWR from 'swr';
import Link from 'next/link';
import { AlertTriangle, Clock3, ExternalLink, RefreshCw, Repeat2, Wrench } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

const fetcher = async (url: string) => { const r = await fetch(url, { credentials: 'include' }); const p = await r.json().catch(() => null); if (!r.ok) throw new Error(p?.error || 'No se pudo cargar'); return p; };
const money = (value: number) => new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(value || 0);
const hours = (value: number | null) => value == null ? 'Sin base suficiente' : `${new Intl.NumberFormat('es-CL', { maximumFractionDigits: 1 }).format(value)} h`;

export default function ReliabilityPage() {
  const { data, error, isLoading, mutate } = useSWR('/api/maintenance/reliability', fetcher, { revalidateOnFocus: false });
  const summary = data?.summary;
  return <div className="space-y-6">
    <section className="flex flex-col gap-4 border-b border-border/70 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-medium text-muted-foreground">Mantenimiento</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Confiabilidad y fallas repetitivas</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Prioriza recurrencias usando únicamente OT, tiempos detenidos, causas registradas, componentes instalados y costos reales.</p></div><Button variant="outline" onClick={() => void mutate()}><RefreshCw className="mr-2 h-4 w-4"/>Actualizar</Button></section>
    {error ? <Card className="shadow-none"><CardContent className="p-6 text-sm text-muted-foreground">No se pudo calcular la confiabilidad.</CardContent></Card> : null}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[
      ['Equipos con correctivos', summary?.equipmentWithCorrective || 0], ['Con recurrencia', summary?.repeatedFailureEquipment || 0], ['OT correctivas', summary?.correctiveWorkOrders || 0], ['Causas repetidas', summary?.repeatedRootCauses || 0], ['Componentes repetidos', summary?.repeatedComponents || 0], ['Costo correctivo', money(summary?.cost || 0)]
    ].map(([label,value]) => <Card key={String(label)} className="shadow-none"><CardContent className="p-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></CardContent></Card>)}</div>
    <Card className="shadow-none"><CardHeader><CardTitle className="text-lg">Equipos priorizados</CardTitle></CardHeader><CardContent className="p-0">{isLoading ? <div className="p-6 text-sm text-muted-foreground">Calculando recurrencias…</div> : (data?.reliability || []).length === 0 ? <div className="p-8 text-center text-sm text-muted-foreground">No existen OT correctivas con equipo asociado suficientes para calcular recurrencias.</div> : <div className="divide-y">{data.reliability.map((row: any) => <div key={row.assetId} className="p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap gap-2"><Badge variant={row.failures >= 2 ? 'destructive' : 'outline'}>{row.failures} correctivo{row.failures === 1 ? '' : 's'}</Badge>{row.criticality && <Badge variant="secondary">{row.criticality}</Badge>}{row.openCorrective > 0 && <Badge variant="outline">{row.openCorrective} abierta{row.openCorrective === 1 ? '' : 's'}</Badge>}</div><p className="mt-3 font-medium">{row.assetCode ? `${row.assetCode} · ` : ''}{row.assetName}</p><div className="mt-2 grid gap-2 text-sm text-muted-foreground sm:grid-cols-4"><span><Repeat2 className="mr-1 inline h-3.5 w-3.5"/>MTBF observado: {hours(row.observedMtbfHours)}</span><span><Clock3 className="mr-1 inline h-3.5 w-3.5"/>Detención: {hours(row.totalDowntimeHours)}</span><span>Costo: {money(row.totalCost)}</span><span>Preventivos activos: {row.preventiveCount}</span></div></div><Button size="sm" variant="outline" asChild><Link href={`/dashboard/mantenimiento/equipos/${row.assetId}`}><ExternalLink className="mr-2 h-4 w-4"/>Equipo</Link></Button></div>{row.workOrders?.length > 0 && <div className="mt-4 grid gap-2">{row.workOrders.slice(0,4).map((wo: any) => <Link key={wo.id} href={`/dashboard/mantenimiento/ordenes-trabajo/${wo.id}`} className="rounded-md border p-3 text-sm hover:bg-muted"><span className="font-medium">{wo.number || 'OT'} · {wo.title || 'Sin título'}</span><span className="ml-2 text-muted-foreground">{wo.rootCause ? `Causa: ${wo.rootCause}` : 'Sin causa raíz registrada'}</span></Link>)}</div>}</div>)}</div>}</CardContent></Card>
    <div className="grid gap-6 xl:grid-cols-2"><Card className="shadow-none"><CardHeader><CardTitle className="text-lg">Causas raíz repetidas</CardTitle></CardHeader><CardContent className="space-y-3">{(data?.repeatedRootCauses || []).length === 0 ? <p className="text-sm text-muted-foreground">No hay causas raíz repetidas registradas. Motil no infiere causas ausentes.</p> : data.repeatedRootCauses.map((row: any, index: number) => <div key={`${row.assetId}-${index}`} className="rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{row.assetName}</p><p className="mt-1 text-sm">{row.cause}</p></div><Badge variant="destructive">{row.occurrences} veces</Badge></div><p className="mt-2 text-xs text-muted-foreground">Detención {hours(row.downtimeHours)} · {money(row.cost)}</p></div>)}</CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle className="text-lg">Componentes repetidos</CardTitle></CardHeader><CardContent className="space-y-3">{(data?.repeatedComponents || []).length === 0 ? <p className="text-sm text-muted-foreground">No hay componentes instalados repetidamente en OT correctivas con evidencia suficiente.</p> : data.repeatedComponents.map((row: any) => <div key={`${row.assetId}-${row.productId}`} className="rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{row.assetName}</p><p className="mt-1 text-xs text-muted-foreground">Producto canónico: {row.productId}</p></div><Badge variant="outline">{row.occurrences} OT</Badge></div><p className="mt-2 text-xs text-muted-foreground">Cantidad instalada {row.installedQuantity} · {money(row.cost)}</p></div>)}</CardContent></Card></div>
    <Card className="shadow-none"><CardContent className="p-4 text-xs text-muted-foreground"><AlertTriangle className="mr-1 inline h-3.5 w-3.5"/>Una recurrencia indica repetición observada, no diagnóstico ni probabilidad futura. MTBF solo aparece cuando existen eventos consecutivos suficientes.</CardContent></Card>
  </div>;
}
