import type { MaintenanceExpedientRecord } from './cat-938h-n1-batch';

export const generadorAtlasCopcoQas500Batch: MaintenanceExpedientRecord[] = [
  {
    id: 'qas500-2023-02-10-pauta-250h',
    source: 'WhatsApp Image 2026-07-29 at 14.45.50 (1) (1).jpeg',
    date: '2023-02-10',
    title: 'Pauta de mantencion 250 hrs',
    kind: 'pauta',
    canonicalSection: 'ot_historica',
    summary: 'Pauta de mantencion preventiva del generador Atlas Copco QAS 500 KVA con cambio de aceite y control visual de componentes.',
    components: ['aceite de motor', 'filtros', 'neumaticos', 'estructura'],
    extractedData: {
      asset: 'Generador Atlas Copco QAS 500 KVA',
      maintenance_cycle: '250 hrs',
      oil_liters: 40,
      filters: 3,
      note: 'inspeccion general N/A en la mayoria de los puntos',
    },
  },
  {
    id: 'qas500-2024-07-29-pauta-250h',
    source: 'WhatsApp Image 2026-07-29 at 14.47.24 (1) (1).jpeg',
    date: '2024-07-29',
    title: 'Pauta de mantencion 250 hrs',
    kind: 'pauta',
    canonicalSection: 'ot_historica',
    summary: 'Pauta de mantencion 250 hrs del generador Atlas Copco QAS 500 KVA con registro de cambio de aceite y control de estructura.',
    components: ['aceite de motor', 'filtros', 'neumaticos', 'estructura'],
    extractedData: {
      asset: 'Generador Atlas Copco QAS 500 KVA',
      maintenance_cycle: '250 hrs',
      oil_liters: 40,
      filters: 3,
    },
  },
  {
    id: 'qas500-2025-06-30-inyectores',
    source: 'WhatsApp Image 2026-07-29 at 14.47.14 (2) (1).jpeg',
    date: '2025-06-30',
    title: 'Cambio de inyectores',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Se realizan trabajos de mantencion preventiva con cambio de los seis inyectores y regulacion de valvulas.',
    cause: 'Inyectores en mantencion preventiva.',
    solution: 'Cambio de inyectores y regulacion de valvulas.',
    components: ['6 inyectores', 'valvulas'],
    extractedData: {
      asset: 'Generador Atlas Copco QAS 500 KVA',
      maintenance_cycle: 'preventiva',
    },
  },
  {
    id: 'qas500-2026-01-16-estanque-combustible',
    source: 'WhatsApp Image 2026-07-29 at 14.47.08 (3).jpeg',
    date: '2026-01-16',
    title: 'Reparacion de estanque de combustible',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Se realiza reparacion del estanque de combustible por fisura y posterior fuga de combustible.',
    cause: 'Fisura en el estanque de combustible.',
    solution: 'Reparacion del estanque de combustible y control de fuga.',
    components: ['estanque de combustible'],
    extractedData: {
      asset: 'Generador Atlas Copco QAS 500 KVA',
      system: 'combustible',
    },
  },
  {
    id: 'qas500-2026-01-31-bomba-agua-termostato',
    source: 'WhatsApp Image 2026-07-29 at 14.47.25 (1) (1).jpeg',
    date: '2026-01-31',
    title: 'Cambio de bomba de agua y termostato',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Se cambian bomba de agua, tensor y correa de accesorios, termostato y refrigerante para dejar el equipo operativo.',
    cause: 'Fuga externa en bomba de agua y desgaste de componentes asociados.',
    solution: 'Cambio de bomba de agua, termostato, tensor de correa y correa de accesorios.',
    components: ['bomba de agua', 'termostato', 'tensor', 'correa de accesorios', 'refrigerante'],
    extractedData: {
      asset: 'Generador Atlas Copco QAS 500 KVA',
      system: 'refrigeracion',
    },
  },
  {
    id: 'qas500-2026-02-26-alternador',
    source: 'WhatsApp Image 2026-07-29 at 14.47.24 (2) (1).jpeg',
    date: '2026-02-26',
    title: 'Cambio de alternador',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'El equipo ingresa con codigo de falla activo por alternador en mal estado y se reemplaza el alternador.',
    cause: 'Alternador en mal estado.',
    solution: 'Cambio de alternador.',
    components: ['alternador'],
    extractedData: {
      asset: 'Generador Atlas Copco QAS 500 KVA',
      system: 'carga electrica',
    },
  },
];

export const generadorAtlasCopcoQas500Summary = {
  asset: 'Generador Atlas Copco QAS 500 KVA',
  location: 'Mina Peumo',
  records: generadorAtlasCopcoQas500Batch.length,
  categories: {
    ot_historica: generadorAtlasCopcoQas500Batch.filter((item) => item.canonicalSection === 'ot_historica').length,
    arbol_fallas: generadorAtlasCopcoQas500Batch.filter((item) => item.canonicalSection === 'arbol_fallas').length,
    componentes: generadorAtlasCopcoQas500Batch.filter((item) => item.canonicalSection === 'componentes').length,
  },
};
