import type { MaintenanceExpedientRecord } from './cat-938h-n1-batch';

export const scoop7AtlasSt1030Batch: MaintenanceExpedientRecord[] = [
  {
    id: 'scoop7-2026-01-29-planillas-mal-estado',
    source: 'WhatsApp Image 2026-07-29 at 14.52.56.jpeg',
    date: '2026-01-29',
    title: 'Planillas en mal estado',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Se detectan planillas golpeadas y se cambia el conjunto completo de puerta y vidrio trasero.',
    cause: 'Planillas golpeadas.',
    solution: 'Cambio de planillas.',
    components: ['planillas de puerta', 'vidrio trasero'],
    extractedData: {
      asset: 'Scoop N°7',
      model: 'Atlas ST1030',
      location: 'Taller Mina Peumo',
    },
  },
  {
    id: 'scoop7-2026-02-10-flexible-transmision',
    source: 'WhatsApp Image 2026-07-29 at 14.53.12.jpeg',
    date: '2026-02-10',
    title: 'Fuga en transmision',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Se corrige fuga de aceite de transmision HD30 en flexible de 1" causado por golpes con piedras.',
    cause: 'Flexible de 1" dañado por piedras grandes.',
    solution: 'Cambio de flexible y ajuste de largo para evitar nuevas roturas.',
    components: ['flexible 1"', 'aceite HD30'],
    extractedData: {
      asset: 'Scoop N°7',
      model: 'Atlas ST1030',
      system: 'transmision',
    },
  },
  {
    id: 'scoop7-2026-02-12-lavado-sin-ejecutar',
    source: 'WhatsApp Image 2026-07-29 at 14.53.13.jpeg',
    date: '2026-02-12',
    title: 'Equipo sucio, lavado pendiente',
    kind: 'observacion',
    canonicalSection: 'pendiente_clasificar',
    summary: 'El equipo se recibe con suciedad y se deja sin lavado completo por condicion operativa.',
    cause: 'No se realiza lavado en turno.',
    solution: 'Equipo se entrega sin lavado completo.',
    extractedData: {
      asset: 'Scoop N°7',
      model: 'Atlas ST1030',
      note: 'condicion de suciedad',
    },
  },
  {
    id: 'scoop7-2026-02-19-correas-mal-estado',
    source: 'WhatsApp Image 2026-07-29 at 14.53.14.jpeg',
    date: '2026-02-19',
    title: 'Correas en mal estado',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Se detectan correas con mas de 500 hrs y se reemplazan para recuperar operacion.',
    cause: 'Correas con mas de 500 hrs.',
    solution: 'Cambio de correa y rodamientos de tensor.',
    components: ['correa', 'rodamientos de tensor'],
    extractedData: {
      asset: 'Scoop N°7',
      model: 'Atlas ST1030',
      maintenance_reason: 'correas deterioradas',
    },
  },
  {
    id: 'scoop7-2026-02-24-fuga-hidraulica-pilotaje',
    source: 'WhatsApp Image 2026-07-29 at 14.53.15.jpeg',
    date: '2026-02-24',
    title: 'Fugas hidraulicas y pilotaje',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Se eliminan fugas hidraulicas y se corrigen lineas de pilotaje y adaptador dañado.',
    cause: 'Flexible y adaptador con daño.',
    solution: 'Cambio de flexible y adaptador; se agrega aceite hidraulico.',
    components: ['flexible hidraulico', 'adaptador', 'aceite hidraulico'],
    extractedData: {
      asset: 'Scoop N°7',
      model: 'Atlas ST1030',
      system: 'hidraulico',
    },
  },
  {
    id: 'scoop7-2026-03-04-ac-condensacion',
    source: 'WhatsApp Image 2026-07-29 at 14.53.15 (2).jpeg',
    date: '2026-03-04',
    title: 'Problemas de A/C',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'El equipo sale de interior mina por problemas en A/C y se reemplaza la manguera de condensacion.',
    cause: 'Manguera de condensacion en mal estado.',
    solution: 'Cambio de manguera de condensacion y recarga de A/C.',
    components: ['manguera de condensacion', 'refrigerante'],
    extractedData: {
      asset: 'Scoop N°7',
      model: 'Atlas ST1030',
      system: 'A/C',
    },
  },
  {
    id: 'scoop7-2026-03-05-ac-termostato',
    source: 'WhatsApp Image 2026-07-29 at 14.53.16.jpeg',
    date: '2026-03-05',
    title: 'Corte en termostato de A/C',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Al terminar turno el equipo presenta corte en el termostato del A/C.',
    cause: 'Cables y contactos en mal estado.',
    solution: 'Reparacion de cables y contactos para dejar operativo el A/C.',
    components: ['termostato A/C', 'cables', 'contactos'],
    extractedData: {
      asset: 'Scoop N°7',
      model: 'Atlas ST1030',
      system: 'A/C',
    },
  },
  {
    id: 'scoop7-2026-03-07-neumatico-pos1',
    source: 'WhatsApp Image 2026-07-29 at 14.53.17.jpeg',
    date: '2026-03-07',
    title: 'Neumatico pinchado posicion N°1',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Se cambia neumatico de posicion N°1 por pinchazo en interior mina.',
    cause: 'Pinchazo en interior mina, estacion 5.',
    solution: 'Cambio de neumatico posicion N°1.',
    components: ['neumatico posicion N°1'],
    extractedData: {
      asset: 'Scoop N°7',
      model: 'Atlas ST1030',
      location: 'Interior mina',
      station: '5',
    },
  },
  {
    id: 'scoop7-2026-03-18-neumatico-mal-estado',
    source: 'WhatsApp Image 2026-07-29 at 14.53.18.jpeg',
    date: '2026-03-18',
    title: 'Neumatico en mal estado',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Se cambia neumatico por mal estado en posicion N°1.',
    cause: 'Desgaste y mal estado del neumatico.',
    solution: 'Cambio de neumatico posicion N°1.',
    components: ['neumatico posicion N°1'],
    extractedData: {
      asset: 'Scoop N°7',
      model: 'Atlas ST1030',
    },
  },
  {
    id: 'scoop7-2026-03-24-fugas-hidraulicas',
    source: 'WhatsApp Image 2026-07-29 at 14.53.19.jpeg',
    date: '2026-03-24',
    title: 'Eliminar fugas hidraulicas',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Se eliminan fugas hidraulicas, pilotaje y se deja el equipo operativo con reposicion de aceite.',
    cause: 'Flexible 1" y piloto con fugas.',
    solution: 'Cambio de flexible 1", lineas de pilotaje y 10 lts de aceite hidraulico.',
    components: ['flexible 1"', 'linea de pilotaje', 'aceite hidraulico'],
    extractedData: {
      asset: 'Scoop N°7',
      model: 'Atlas ST1030',
      oilAddedLiters: 10,
    },
  },
];

export const scoop7AtlasSt1030Summary = {
  asset: 'Scoop N°7 Atlas ST1030',
  location: 'Mina Peumo',
  records: scoop7AtlasSt1030Batch.length,
  categories: {
    ot_historica: scoop7AtlasSt1030Batch.filter((item) => item.canonicalSection === 'ot_historica').length,
    arbol_fallas: scoop7AtlasSt1030Batch.filter((item) => item.canonicalSection === 'arbol_fallas').length,
    componentes: scoop7AtlasSt1030Batch.filter((item) => item.canonicalSection === 'componentes').length,
  },
};
