import type { MaintenanceExpedientRecord } from './cat-938h-n1-batch';

export const volkswagenAmarokLvgx54Batch: MaintenanceExpedientRecord[] = [
  {
    id: 'amarok-2023-12-14-lavado-fluidos',
    source: 'codex-clipboard-4cd36ac9-ebec-4257-9e3a-ab8989a0c9b1.png',
    date: '2023-12-14',
    title: 'Lavado y revisión de fluidos',
    kind: 'pauta',
    canonicalSection: 'ot_historica',
    summary: 'Se realiza lavado de equipo y revisión de niveles de fluidos como parte del servicio base.',
    cause: 'Revisión preventiva.',
    solution: 'Lavado de equipo y revisión de niveles de fluidos.',
    components: ['limpiaparabrisas'],
    extractedData: {
      asset: 'Volkswagen Amarok SKYB-57',
      mechanic: 'Eders Aguirre',
      supervisor: 'Esteban Díaz',
      startTime: '11:00',
      endTime: '12:00',
      km: 'desconocido',
      entregadoPor: 'Esteban Díaz',
    },
  },
  {
    id: 'amarok-2023-12-28-10000kms',
    source: 'codex-clipboard-701c93ca-d606-4e90-8a46-bff8f85796b9.png',
    date: '2023-12-28',
    title: 'Mantención programada 10.000 kms',
    kind: 'pauta',
    canonicalSection: 'ot_historica',
    summary: 'Servicio de mantención preventiva con cambio de filtros y aceite según pauta de 10.000 kms.',
    cause: 'Mantención programada.',
    solution: 'Cambio de aceite, filtro de aire, polen, aceite y combustible; revisión general.',
    components: ['aceite de motor', 'filtro de aire', 'filtro de polen', 'filtro de aceite', 'filtro de combustible'],
    extractedData: {
      asset: 'Volkswagen Amarok SKYB-57',
      mechanic: 'Jose Perez',
      supervisor: 'Esteban Díaz',
      startTime: '08:30',
      endTime: '13:00',
      km: '9856',
      vale: '150884',
    },
  },
  {
    id: 'amarok-2024-03-18-bateria-partida',
    source: 'codex-clipboard-10315e9f-c721-42cd-a717-7b26df1eb922.png',
    date: '2024-03-18',
    title: 'Problemas de partida por batería',
    kind: 'reparacion',
    canonicalSection: 'arbol_fallas',
    summary: 'Se reemplaza la batería por problemas de partida y falla en el sistema eléctrico.',
    cause: 'Batería con falla.',
    solution: 'Cambio de batería de 70 Ah.',
    components: ['batería de 70 Ah'],
    extractedData: {
      asset: 'Volkswagen Amarok SKYB-57',
      mechanic: 'Rodrigo Olmos',
      supervisor: 'Esteban Díaz',
      year: '2020',
      km: '20160',
      system: 'eléctrico',
    },
  },
  {
    id: 'amarok-2024-07-03-10000kms',
    source: 'codex-clipboard-3f7699b8-48d8-4417-b3c0-06a3b5fe0089.png',
    date: '2024-07-03',
    title: 'Mantención programada 10.000 kms con frenos',
    kind: 'pauta',
    canonicalSection: 'ot_historica',
    summary: 'Mantención programada con cambio de consumibles, limpieza de sensor y revisión de frenos.',
    cause: 'Mantención preventiva por kilometraje.',
    solution:
      'Cambio de aceite de motor, filtros, limpieza de sensor de filtro de petróleo y mantención a frenos.',
    components: [
      'aceite 5W30',
      'filtro de aceite',
      'filtro de combustible',
      'filtro de aire',
      'filtro de aire acondicionado',
      'sensor filtro de combustible',
      'tambor de freno',
    ],
    extractedData: {
      asset: 'Volkswagen Amarok SKYB-57',
      mechanic: 'Rodrigo Olmos',
      supervisor: 'Esteban Díaz',
      year: '2020',
      km: '20160',
      oilLiters: 11,
    },
  },
];

export const volkswagenAmarokLvgx54Summary = {
  asset: 'Volkswagen Amarok SKYB-57',
  location: 'Planta',
  records: volkswagenAmarokLvgx54Batch.length,
  categories: {
    ot_historica: volkswagenAmarokLvgx54Batch.filter((item) => item.canonicalSection === 'ot_historica').length,
    arbol_fallas: volkswagenAmarokLvgx54Batch.filter((item) => item.canonicalSection === 'arbol_fallas').length,
    componentes: volkswagenAmarokLvgx54Batch.filter((item) => item.canonicalSection === 'componentes').length,
  },
};
